# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  PROJECT_PATH: './src/SimpleApi/SimpleApi.sln'
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore $PROJECT_PATH
    - name: Build
      run: dotnet build $PROJECT_PATH --no-restore
    - name: Test
      run: dotnet test $PROJECT_PATH --no-build --verbosity normal
